checks:
    go: true

build:
    environment:
        go: go1.12.6

    nodes:
        analysis:
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    - golint-run

filter:
    excluded_paths:
        - api/admin/namedserver_test.go
        - api/admin/node_test.go
        - api/admin/report_test.go
        - api/admin/reportingevent_test.go
        - api/admin/speedtestnetserver_test.go
        - api/admin/tag_test.go
        - api/admin/user_test.go
        - api/admin/version_test.go
        - agent/config/main_test.go
        - agent/hello/main_test.go
        - agent/tasklog/main_test.go
        - lib/ipinfo/ipinfo_test.go
        - lib/reporting/snapshot_test.go
        - lib/speedtestnet/speedtestnet_test.go