checks:
    go: true

build:
    environment:
        go: go1.12.6

    nodes:
        analysis:
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    - golint-run

filter:
    excluded_paths:
        - */*/namedserver_test.go
        - */*/node_test.go
        - */*/report_test.go
        - */*/reportingevent_test.go
        - */*/speedtestnetserver_test.go
        - */*/tag_test.go
        - */*/user_test.go
        - */*/version_test.go
        - */*/main_test.go
        - */*/helpers_test.go
        - */*/snapshot_test.go
        - */*/speedtestnet_test.go