version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
    env_file:
      - ./local.env
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["bash"]

  dynamo:
    image: dwmkerr/dynamodb
    command: "-sharedDb"
    hostname: dynamo
    environment:
      - reschedule=on-node-failure

  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name speedsnitch_local_data --attribute-definitions AttributeName=ID,AttributeType=S --key-schema AttributeName=ID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=50,WriteCapacityUnits=50 --endpoint-url http://dynamo:8000"
    links:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=us-east-1

  test:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - dynamo
    environment:
      - STAGE=local
      - dataTable=speedsnitch_local_data
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["./run-debug.sh"]