version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    env_file:
      - ./local.env
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["bash"]

  db:
    image: silintl/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass

  test:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["./run-debug.sh"]