version: "3"

services:

  app:
    build: .
    environment:
      GOOS: linux
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      SES_RETURN_TO_ADDR: no_reply@example.com
    env_file:
      - ./local.env
    volumes:
      - ./:/src
    command: ["bash"]

  db:
    image: mariadb:10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass

  test:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
    volumes:
      - ./:/src
    command: ["./run-debug.sh"]
