version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
      - ./aws.credentials:/root/.aws/credentials
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["bash"]
