version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GOOS: linux
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    env_file:
      - ./local.env
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["bash"]

  dynamo:
    image: cnadiminti/dynamodb-local
    command: "-sharedDb -inMemory"
    hostname: dynamo
    ports:
      - "8000:8000"
    environment:
      reschedule: on-node-failure

  init-dynamo:
    image: garland/aws-cli-docker
    command: "/init-dynamodb.sh"
    volumes:
      - ./codeship/init-dynamodb.sh:/init-dynamodb.sh
    depends_on:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DYNAMODB_ENDPOINT=http://dynamo:8000

  db:
    image: silintl/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: pass

  test:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - init-dynamo
    environment:
      AWS_ACCESS_KEY_ID: 0
      AWS_SECRET_ACCESS_KEY: 0
      AWS_DEFAULT_REGION: us-east-1
      AWS_DYNAMODB_ENDPOINT: http://dynamo:8000
    volumes:
      - ./:/go/src/github.com/silinternational/speed-snitch-admin-api
    working_dir: /go/src/github.com/silinternational/speed-snitch-admin-api
    command: ["./run-debug.sh"]