# For full config options, check the docs:
#    docs.serverless.com

service: speedsnitch

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
      Resource:
        - Fn::GetAtt:
          - nodesTable
          - Arn
        - Fn::GetAtt:
          - usersTable
          - Arn
        - Fn::GetAtt:
          - tagsTable
          - Arn
        - Fn::GetAtt:
          - versionsTable
          - Arn

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    namespace: ${self:custom.namespace}
    nodeTable: ${self:custom.nodeTable}
    userTable: ${self:custom.userTable}
    tagTable: ${self:custom.tagTable}
    versionTable: ${self:custom.versionTable}

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}_${self:custom.stage}
  nodeTable: ${self:custom.namespace}_node
  userTable: ${self:custom.namespace}_user
  tagTable: ${self:custom.namespace}_tag
  versionTable: ${self:custom.namespace}_version

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
      handler: bin/hello
      events:
        - http:
            path: hello
            method: post
  node:
      handler: bin/node
      events:
        - http:
            path: node
            method: GET
        - http:
            path: /node/{macAddr}
            method: GET
            request:
              parameters:
                paths:
                  macAddr: true
        - http:
            path: /node/{macAddr}
            method: PUT
            request:
              parameters:
                paths:
                  macAddr: true
        - http:
            path: /node/{macAddr}
            method: DELETE
            request:
              parameters:
                paths:
                  macAddr: true
  tag:
      handler: bin/tag
      events:
        - http:
            path: tag
            method: GET
        - http:
            path: tag
            method: POST
        - http:
            path: /tag/{name}
            method: GET
            request:
              parameters:
                paths:
                  name: true
        - http:
            path: /tag/{name}
            method: PUT
            request:
              parameters:
                paths:
                  name: true
        - http:
            path: /tag/{name}
            method: DELETE
            request:
              parameters:
                paths:
                  name: true
  user:
      handler: bin/user
      events:
        - http:
            path: user
            method: GET
        - http:
            path: user
            method: POST
        - http:
            path: /user/{id}
            method: GET
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: PUT
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: DELETE
            request:
              parameters:
                paths:
                  id: true
  version:
      handler: bin/version
      events:
        - http:
            path: version
            method: GET
        - http:
            path: version
            method: POST
        - http:
            path: /version/{number}
            method: GET
            request:
              parameters:
                paths:
                  number: true
        - http:
            path: /version/{number}
            method: PUT
            request:
              parameters:
                paths:
                  number: true
        - http:
            path: /version/{number}
            method: DELETE
            request:
              parameters:
                paths:
                  number: true

resources:
  Resources:
    nodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.nodeTable}'
        AttributeDefinitions:
          - AttributeName: MacAddr
            AttributeType: S
        KeySchema:
          - AttributeName: MacAddr
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.userTable}'
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    tagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.tagTable}'
        AttributeDefinitions:
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: Name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    versionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.versionTable}'
        AttributeDefinitions:
          - AttributeName: Number
            AttributeType: S
        KeySchema:
          - AttributeName: Number
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1