service: speedsnitch-agent

frameworkVersion: ^3.7.0

provider:
  name: aws
  runtime: go1.x
  timeout: 30
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    apiKeys:
      - name: ${self:custom.namespace}-agent
        value: ${env:AGENT_API_TOKEN}
  vpc:
    securityGroupIds:
      - ${env:VPC_SG_ID}
    subnetIds:
      - ${env:VPC_SUBNET1}
      - ${env:VPC_SUBNET2}
      - ${env:VPC_SUBNET3}

  environment:
    stage: ${sls:stage}
    namespace: ${self:custom.namespace}
    downloadBaseUrl: ${env:DOWNLOAD_BASE_URL}
    MYSQL_HOST: ${env:MYSQL_HOST}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASS: ${env:MYSQL_PASS}
    MYSQL_DB: ${env:MYSQL_DB}


plugins:
  - serverless-domain-manager

custom:
  namespace: ${self:service}_${sls:stage}
  customDomain:
    domainName: ${env:CUSTOM_DOMAIN_NAME}
    basePath: ''
    stage: ${sls:stage}
    createRoute53Record: false
    certificateName: ${env:CERT_NAME}
    enabled: true

package:
 patterns:
   - '!./**'
   - ../../bin/hello
   - ../../bin/config
   - ../../bin/tasklog

functions:
  hello:
      handler: bin/hello
      events:
        - http:
            path: hello
            method: post
            private: true
  config:
      handler: bin/config
      events:
        - http:
            path: config/{macAddr}
            method: get
            private: true
            request:
              parameters:
                paths:
                  macAddr: true
  log:
      handler: bin/tasklog
      events:
        - http:
            path: log/{macAddr}/{entryType}
            method: post
            private: true
            request:
              parameters:
                paths:
                  macAddr: true
                  entryType: true
