# For full config options, check the docs:
#    docs.serverless.com

service: speedsnitch

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x
  apiKeys:
    - ${self:custom.namespace}-admin
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
      Resource:
        - Fn::GetAtt:
          - dataTable
          - Arn
        - Fn::GetAtt:
          - taskLogTable
          - Arn

  # you can define service wide environment variables here
  environment:
    stage: ${self:custom.stage}
    namespace: ${self:custom.namespace}
    dataTable: ${self:custom.dataTable}
    taskLogTable: ${self:custom.taskLogTable}

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: ${self:service}_${self:custom.stage}
  dataTable: ${self:custom.namespace}_data
  taskLogTable: speedsnitch_${self:custom.stage}_task_log

package:
 exclude:
   - ./**
 include:
   - ../../bin/**

functions:
  node:
      handler: bin/node
      events:
        - http:
            path: node
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: /node/{macAddr}
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  macAddr: true
        - http:
            path: /node/{macAddr}
            method: PUT
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  macAddr: true
        - http:
            path: /node/{macAddr}
            method: DELETE
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  macAddr: true
  tag:
      handler: bin/tag
      events:
        - http:
            path: tag
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: tag
            method: POST
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: /tag/{name}
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  name: true
        - http:
            path: /tag/{name}
            method: PUT
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  name: true
        - http:
            path: /tag/{name}
            method: DELETE
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  name: true
  user:
      handler: bin/user
      events:
        - http:
            path: user
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: user
            method: POST
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: /user/{id}
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: PUT
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: DELETE
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  id: true
  version:
      handler: bin/version
      events:
        - http:
            path: version
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: version
            method: POST
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
        - http:
            path: /version/{number}
            method: GET
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  number: true
        - http:
            path: /version/{number}
            method: PUT
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  number: true
        - http:
            path: /version/{number}
            method: DELETE
            #private: true
            cors:
              origin: "*"
              headers:
                - Content-Type
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-User-Agent
              allowCredentials: true
            request:
              parameters:
                paths:
                  number: true

resources:
  Resources:
    nodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.dataTable}'
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    taskLogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: '${self:custom.taskLogTable}'
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
          - AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
