service: speedsnitch

frameworkVersion: ^3.7.0

provider:
  name: aws
  runtime: go1.x
  timeout: 30
  versionFunctions: false
  logRetentionInDays: 14
  apiGateway:
    apiKeys:
      - ${self:custom.namespace}-admin
  vpc:
    securityGroupIds:
      - ${env:VPC_SG_ID}
    subnetIds:
      - ${env:VPC_SUBNET1}
      - ${env:VPC_SUBNET2}
      - ${env:VPC_SUBNET3}

  environment:
    stage: ${sls:stage}
    namespace: ${self:custom.namespace}
    downloadBaseUrl: ${env:DOWNLOAD_BASE_URL}
    MYSQL_HOST: ${env:MYSQL_HOST}
    MYSQL_USER: ${env:MYSQL_USER}
    MYSQL_PASS: ${env:MYSQL_PASS}
    MYSQL_DB: ${env:MYSQL_DB}
    SES_RETURN_TO_ADDR: ${env:SES_RETURN_TO_ADDR}
    SES_AWS_REGION: ${env:AWS_REGION}

  stackTags:
    app: speedsnitch
    app_env: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "*"

custom:
  namespace: ${self:service}_${sls:stage}

package:
 patterns:
   - '!./**'
   - ../../bin/admin
   - ../../bin/speedtestnetserverupdate
   - ../../bin/alerts
   - ../../bin/dailysnapshot
   - ../../bin/migrations

functions:
  dailysnapshot:
      handler: bin/dailysnapshot
      timeout: 300
      events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
        - schedule: cron(0 1 * * ? *) # every day at 1 AM UTC

  alerts:
      handler: bin/alerts
      timeout: 300
      events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
        - schedule: cron(30 1 ? * MON,THU *) # at 1:30 AM UTC on Monday and Thursday

  migrations:
      handler: bin/migrations
      events:
        - schedule:
            rate: rate(365 days)
            enabled: true

  admin:
      handler: bin/admin

      events:
        ##############
        # node events
        ##############
        - http:
            path: /node
            method: GET
            private: true

        - http:
            path: /node/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /node/{id}/tag
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /node/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /node/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true

        ################
        # report events
        ################
        - http:
            path: /report/node/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /report/node/{id}/event
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /report/node/{id}/raw
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true

        ################
        # tag events
        ################
        - http:
            path: /tag
            method: GET
            private: true

        - http:
            path: /tag
            method: POST
            private: true

        - http:
            path: /tag/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /tag/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /tag/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true

        #####################
        # namedserver events
        #####################
        - http:
            path: /namedserver
            method: GET
            private: true
        - http:
            path: /namedserver
            method: POST
            private: true
        - http:
            path: /namedserver/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /namedserver/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /namedserver/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true

        #############################
        # speedtestnetserver events
        #############################
        - http:
            path: /speedtestnetserver/country
            method: GET
            private: true
        - http:
            path: /speedtestnetserver/country/{countryCode}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  countryCode: true
        - http:
            path: /speedtestnetserver/country/{countryCode}/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  countryCode: true
                  id: true

        ##############
        # user events
        ##############
        - http:
            path: /user
            method: GET
            private: true

        - http:
            path: /user
            method: POST
            private: true

        - http:
            path: /user/me
            method: GET
            private: true

        - http:
            path: /user/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /user/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true

        #################
        # version events
        #################
        - http:
            path: /version
            method: GET
            private: true

        - http:
            path: /version
            method: POST
            private: true

        - http:
            path: /version/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /version/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /version/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true

        ###################
        # reporting events
        ###################
        - http:
            path: /reportingevent
            method: GET
            private: true

        - http:
            path: /reportingevent
            method: POST
            private: true

        - http:
            path: /reportingevent/{id}
            method: GET
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /reportingevent/{id}
            method: PUT
            private: true
            request:
              parameters:
                paths:
                  id: true
        - http:
            path: /reportingevent/{id}
            method: DELETE
            private: true
            request:
              parameters:
                paths:
                  id: true
